## 1. Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2. Create a vector with values ranging from 10 to 49.

In [2]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
x=np.array([1,2,0,0,4,0])
print("indices of non-zero elements are:",np.nonzero(x))

indices of non-zero elements are: (array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
import random
random.seed(10)
x=np.random.random(size=(10,10))
print("minimum value:",x.min())
print("maximum value:",x.max())
print(x)

minimum value: 0.010273241166361746
maximum value: 0.9934801882580969
[[0.69247835 0.52331298 0.23671348 0.74098752 0.65862086 0.73708657
  0.33040053 0.59697637 0.26397198 0.2263495 ]
 [0.93293735 0.85474671 0.5791615  0.21205097 0.09356606 0.99348019
  0.55009209 0.86048331 0.84318759 0.61287092]
 [0.37327181 0.84733661 0.1846026  0.93612871 0.71595991 0.7316266
  0.73625526 0.33816418 0.49786797 0.77236344]
 [0.34738172 0.12872581 0.1853716  0.43832446 0.99081996 0.40531183
  0.53836481 0.52147961 0.78487438 0.1368305 ]
 [0.34962166 0.30259769 0.92396279 0.60756169 0.3493314  0.9743896
  0.66303215 0.39112551 0.06992356 0.11284161]
 [0.25032353 0.147946   0.28243351 0.52001859 0.09259517 0.03827176
  0.10176551 0.95646138 0.35705944 0.26434088]
 [0.0735936  0.48076331 0.26219922 0.33939667 0.1555383  0.45770951
  0.49829081 0.43489322 0.6050932  0.88030693]
 [0.87474272 0.21480801 0.24528346 0.03797191 0.01690339 0.2263564
  0.29789741 0.26527066 0.05077372 0.25405572]
 [0.09632119 

## 6. Create a random vector of size 30 and find the mean value.

In [6]:
arr=np.random.random((5,6))
Mean_value_of_the_matrix=np.mean(arr)
print("mean:",Mean_value_of_the_matrix)

mean: 0.538963250113441
